### ISSUE TITLE
update roadmap

### ISSUE THREAD

**Issue by dromzeh** [dromzeh/discord-custom-stream-status#2]
- [ ] Move from `python` to `node.js (javascript)` (w/ `pnpm` manager, `discord-rpc` package)
- [ ] Make the code actually work
- [ ] Allow for better `customization`.
- [ ] Update `CLI` to be more user friendly.

**Comment by dromzeh** [comment]
could lowkey move this to ratatui (see: https://github.com/dromzeh/hyv-fps-unlocker/issues/13) - forgot i made this
